### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ksafranski** [TechnologyAdvice/upyet#1]
Develop core functionality based on [README](README.md) specifications and options and release initial version on NPM.

**Comment by TomFrost** [comment]
When using as a module, you get to specify retries and timeout; on the CLI, only timeout is available. It would be good to either centralize both on having both options, or in having only timeout (internally deciding how many retries are appropriate).

While the first option is more flexible, I really like the simplicity of the second option.

**Comment by TomFrost** [comment]
Er, ignore me, retries is in the CLI -- it's just not in the readme!

**Comment by ksafranski** [comment]
yeah, I'll add it now. Need to clean that up a bit...

**Comment by taghost** [comment]
Top of readme `Paralell` should be `Parallel`

**Comment by taghost** [comment]
Typo `designatoion` on https://github.com/TechnologyAdvice/upyet/blob/master/test/fixtures/service.js#L6

**Comment by taghost** [comment]
I tried to walk through all the logic before asking this, but still not sure... It looks to me that https://github.com/TechnologyAdvice/upyet/blob/master/upyet.js#L54 should be `>` instead of `>=` For example, if your retry limit is 1, and this is the first attempt then it's already going to reject?

**Comment by ksafranski** [comment]
It only calls `checkRetry` if the connection is attempted and fails, so, yes - it would reject (_after_) the first attempt if the retry is `1`.

**Comment by taghost** [comment]
AH, I see now :)

**Comment by taghost** [comment]
Typo `Alloted` on https://github.com/TechnologyAdvice/upyet/blob/master/cli.js#L15

**Comment by taghost** [comment]
https://github.com/TechnologyAdvice/upyet/blob/master/cli.js#L108 `called` flows better

**Comment by taghost** [comment]
https://github.com/TechnologyAdvice/upyet/blob/master/test/upyet.spec.js#L42 Perhaps extra word `at`?
